```yaml
name: Run R Script

on: [push]

jobs:
  run-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("ggplot2", "dplyr"))'
      - name: Run script
        run: Rscript script.R
      - name: Upload plot
        uses: actions/upload-artifact@v2
        with:
          name: plot
          path: N_accumulation_plot.png
